### ISSUE TITLE
No Quiver dependency matching versions required

### ISSUE THREAD

**Issue by Creeves** [filiph/markov#1]
Hi there,

When I create a simple pubspec.yaml with only
```
dependencies:
 markov: ^2.0.0
```

I get the following errors running `pub get`:
```
Resolving dependencies... (2.9s)
Package quiver has no versions that match >=2.0.0 <3.0.0 derived from:
- markov 2.0.0 depends on version ^2.0.0
```

Should there be a version of the quiver page in this range that markov expects to use?

**Comment by filiph** [comment]
Good catch! You're probably using Dart 1. I _thought_ I still support Dart 1 with the `2.0.0` version of `pkg:markov`, but since I depend on `quiver` version `2.0.0`, I do.

Let me fix this.
